documentation(EJ2-63916): Browser height limitation.
syncfusion-content/ej2-asp-core-mvc-docs pull request #1176
Opened 2022-11-16 13:57 UTC by sharmi70

2022-11-16 13:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/console)**

2022-11-16 14:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1437/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-16 14:18 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1438/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-11-16 14:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/console)**

2022-11-16 14:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1439/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-17 07:33 UTC, florenceliliana requested changes

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +You can load millions of records in the Grid by using virtual scrolling where grid loads and renders rows in on-demand while scrolling vertically. As a result, Grid lighten the browser’s load by mini
You can load millions of records in the Grid by using virtual scrolling, where the grid loads and renders rows on-demand while scrolling vertically. As a result, Grid lightens the browser’s load by minimizing the DOM elements and rendering elements visible in the viewport. The height of the grid is calculated using the Total Records Count * [Row Height](https://help.syncfusion.com/cr/aspnetcore-js2/Syncfusion.EJ2.Grids.Grid.html#Syncfusion_EJ2_Grids_Grid_RowHeight) property.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +The browser has some maximum pixel height limitation for scroll bar element. The content placed above the maximum height can't be scrolled, if the element height is greater than the browser's maximum
The browser has some maximum pixel height limitations for the scroll bar element. The content placed above the maximum height can't be scrolled if the element height is greater than the browser's maximum height limit. The browser height limit affects the virtual scrolling of the grid. When a large number of records are bound to the Grid, it can only display the records until the maximum height limit of the browser. Once the browser's height limit is reached while scrolling, the user won't able to scroll further to view the remaining records.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +For example, if the row height is set as 30px and the total record count will be 1000000(1 million), then the height of the grid element will be 30,000,000 pixels. In this case, the browser's maximum
For example, if the row height is set as 30px and the total record count is 1000000(1 million), then the height of the grid element will be 30,000,000 pixels. In this case, the browser's maximum height limit for a div is about 22,369,600 (The maximum pixel height limitation differs for different browsers). The records above the maximum height limit of the browser can't be scrolled.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +This height limitation is not related to Grid component. Its fully depend on the default behaviour of the browser. The same issue reproduced in the normal html table too.
This height limitation is not related to the Grid component. It fully depends on the default behavior of the browser. The same issue is reproduced in the normal HTML table too.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +Grid component aslo faced the same issue as mentioned in the below image.
Grid component also faced the same issue as mentioned in the below image.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +You can prevent the height limitation problem in browser when scrolling through the millions of records by loading the segment of data through different strategy.
You can prevent the height limitation problem in the browser when scrolling through millions of records by loading the segment of data through different strategy.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +In the following sample, Grid is rendered with a large number of records(nearly 2 million). Here, you can scroll 0.5 million records at a time in Grid. Once you reach the last page of 0.5 million rec
In the following sample, Grid is rendered with a large number of records(nearly 2 million). Here, you can scroll 0.5 million records at a time in Grid. Once you reach the last page of 0.5 million records, the **Load Next Set** button will be shown at the bottom of the Grid. By clicking that button, you can view the next set of 0.5 million records in Grid. Also, the **Load Previous Set** button will be shown at the top of the Grid to load the previous set of 0.5 million records.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +Lets see the step by step procedure for how we can overcome the limitation in Syncfusion Grid component.
Let's see the step by step procedure for how we can overcome the limitation in the Syncfusion Grid component.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +1.	Create custom adaptor by extending UrlAdaptor and bind to the grid dataSource property. In the processQuery method of custom adaptor, we handled the Skip query based on the current page set to per
1. Create a custom adaptor by extending UrlAdaptor and binding it to the grid DataSource property. In the processQuery method of the custom adaptor, we handled the Skip query based on the current page set to perform the data operation with whole records on the server.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +You can reduce the [row height](https://ej2.syncfusion.com/aspnetcore/documentation/grid/row/row-height) using the [RowHeight](https://help.syncfusion.com/cr/aspnetcore-js2/Syncfusion.EJ2.Grids.Grid.
You can reduce the [row height](https://ej2.syncfusion.com/aspnetcore/documentation/grid/row/row-height) using the [RowHeight](https://help.syncfusion.com/cr/aspnetcore-js2/Syncfusion.EJ2.Grids.Grid.html#Syncfusion_EJ2_Grids_Grid_RowHeight) property of the Grid. It will reduce the overall height to accommodate more rows. But this approach optimizes the limitation, but if the height limit is reached after reducing row height also, you have to opt for the previous solution or use paging.

2022-11-17 07:33 UTC, florenceliliana commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/virtual-scroll.md
> +Similar to virtual scrolling, the [paging](https://ej2.syncfusion.com/aspnetcore/documentation/grid/paging) feature also loads the data in on-demand concept. Pagination is also compatible with all th
Similar to virtual scrolling, the [paging](https://ej2.syncfusion.com/aspnetcore/documentation/grid/paging) feature also loads the data in an on-demand concept. Pagination is also compatible with all the other features(Grouping, Editing, etc.) in Grid. So, use the paging feature instead of virtual scrolling to view a large number of records in the Grid without any kind of performance degradation or browser height limitation.

2022-11-17 14:43 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/console)**

2022-11-17 14:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/console)**

2022-11-17 15:00 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/)<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/ej2-asp-core-mvc-docs/1461/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-23 13:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/console)**

2022-11-23 13:16 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/)<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/ej2-asp-core-mvc-docs/1495/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-24 12:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/console)**

2022-11-24 12:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-63916-virtual1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1501/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-11-24 13:12 UTC, MaithiliyK approved these changes
changes are fine

2022-11-24 13:12 UTC, merged