documentation(EJ2-67529): Added chart-combinedYAxis sample.
syncfusion-content/ej2-asp-core-mvc-docs pull request #1358
Opened 2022-12-28 13:29 UTC by Yash58vanth

Added chart-combinedYAxis sample and updated showMemberSeries.

2022-12-28 13:30 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/console)**

2022-12-28 13:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/console)**

2022-12-28 13:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1893/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-28 14:40 UTC, SasthaPrathap commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md
> +![PivotChart with Show member based chart series](images/showMemberSeries.png)
`Show point color based on members in Pivot Chart`

2022-12-28 14:41 UTC, SasthaPrathap requested changes
Check and clear the review feedbacks.

2022-12-28 14:44 UTC, SasthaPrathap commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md
> +![PivotChart with Show member based chart series](images/showMemberSeries.png)
Image look too small. Take image with 720 X 420 px. Tittle not required.

2022-12-28 14:45 UTC, SasthaPrathap requested changes
Check and clear the review feedbacks.

2022-12-29 06:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/console)**

2022-12-29 06:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1923/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-29 07:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/console)**

2022-12-29 08:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1929/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-29 09:38 UTC, Yash58vanth commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md
> +![PivotChart with Show member based chart series](images/showMemberSeries.png)
cleared

2022-12-29 09:38 UTC, SasthaPrathap commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pivot-chart.md
> +![output](images/single-combined-y-axis.png)
add the image caption `Pivot Chart for multiple values in a single y-axis`

2022-12-29 09:39 UTC, SasthaPrathap commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pivot-chart.md
> +![PivotChart with Show member based chart series](images/showMemberSeries.png)
`Show point color based on members in Pivot Chart`

2022-12-29 09:39 UTC, SasthaPrathap commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/pivot-chart.md
> +![output](images/single-combined-y-axis.png)
`Pivot Chart for multiple values in a single y-axis`

2022-12-29 09:40 UTC, SasthaPrathap requested changes
Check and clear the review feedbacks.

2022-12-29 10:05 UTC, SasthaPrathap commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pivot-chart.md
> +When multiple axes are enabled, you can display the same color for each member in the column axis by setting the [`showPointColorByMembers`](https://help.syncfusion.com/cr/aspnetmvc-js2/Syncfusion.EJ
APIs are not related to MVC standard

2022-12-29 10:05 UTC, SasthaPrathap requested changes
Clear the review feedbacks.

2022-12-29 10:14 UTC, Yash58vanth commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.MVC/pivot-chart.md
> +When multiple axes are enabled, you can display the same color for each member in the column axis by setting the [`showPointColorByMembers`](https://help.syncfusion.com/cr/aspnetmvc-js2/Syncfusion.EJ
cleared

2022-12-29 10:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/console)**

2022-12-29 10:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-67529-hot](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1938/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-29 11:04 UTC, SasthaPrathap approved these changes

2022-12-29 11:08 UTC, merged