Documentation(EJ2-66488):Added UG contents for dateRangeTemplate and hideNonWorkingdays properties in ASP MVC/core Scheduler
syncfusion-content/ej2-asp-core-mvc-docs pull request #1382
Opened 2022-12-31 15:32 UTC by VenkateshwaranSaravanakumar

Description:
Added UG contents for newly added feature on tab key navigation using tabIndex property in Tab and Toolbar components.

Areas affected and ensured:
All possible cases

Test cases:
NA

Test bed sample location:
NA

Additional checklist
Did you run the automation against your fix? NA
Is there any API name change? No
Is there any existing behavior change of other features due to this code change? No
Does your new code introduce new warnings or binding errors? No
Does your code pass all FxCop and StyleCop rules? NA
Did you record this case in the unit test or UI test? No

2022-12-31 15:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/console)**

2022-12-31 15:37 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/)<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/ej2-asp-core-mvc-docs/1962/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-12-31 17:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/console)**

2022-12-31 17:09 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/)<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [4](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com:8443/job/Content/job/ej2-asp-core-mvc-docs/1963/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-03 07:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/console)**

2023-01-03 07:10 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/)<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://jenkins.syncfusion.com:8443/job/Content/job/ej2-asp-core-mvc-docs/1973/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-03 07:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/console)**

2023-01-03 07:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-66488-ASPDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1978/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-05 10:11 UTC, VengateshManiraj requested changes

2023-01-05 10:11 UTC, VengateshManiraj commented on ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/header-bar.md
> +The `dateRangeTemplate` option allows you to customize the text content of the date range displayed in the scheduler. By default, the date range text is determined by the scheduler view being used. H
`DateRangeTemplate`

2023-01-05 10:11 UTC, VengateshManiraj commented on ej2-asp-core-mvc/schedule/EJ2_ASP.MVC/resources.md
> +In Scheduler, you can set custom work days for each resource and group the Scheduler by date to display these work days. By default, the Scheduler will show all days when it is grouped by date, even
`HideNonWorkingDays`

2023-01-05 10:11 UTC, VengateshManiraj commented on ej2-asp-core-mvc/code-snippet/tab/tabkeynavigation/razor
> +        new TabTabItem { Header = ViewBag.headerText3, Content = "The command-line compiler, VBC.EXE, is installed as part of the freeware .NET Framework SDK. Mono also includes a command-line VB.NET
Check the property name `TabIndex` or `tabIndex`.

2023-01-05 10:11 UTC, VengateshManiraj commented on ej2-asp-core-mvc/tab/how-to/tab-key-navigation.md
> +The `tabIndex` property of a Tab item is used to enable tab key navigation for that particular item. When a positive value is assigned to the `tabIndex` property, it allows the user to switch focus t
`TabIndex` or `tabIndex`

2023-01-05 10:11 UTC, VengateshManiraj commented on ej2-asp-core-mvc/toolbar/item-configuration.md
> +The `tabIndex` property of a Toolbar item is used to enable tab key navigation for the item. By default, the user can switch between items using the arrow keys, but the `tabIndex` property allows you
`TabIndex` or `tabIndex`

2023-01-05 10:11 UTC, VengateshManiraj commented on ej2-asp-core-mvc/toolbar/item-configuration.md
> +The `tabIndex` property of a Toolbar item is used to enable tab key navigation for the item. By default, the user can switch between items using the arrow keys, but the `tabIndex` property allows you
Ensure this same in sample code too

2023-01-10 04:53 UTC, VenkateshwaranSaravanakumar commented
Changes moved in the hotfix
#1407

2023-01-10 04:53 UTC, closed without merging