documentation(EJ2MVC-490): Updated UG content for rating in Asp.net Core and MVC.
syncfusion-content/ej2-asp-core-mvc-docs pull request #1431
Opened 2023-01-10 13:01 UTC by VigneshwaranGovindharajan

### Feature description

Need to add UG Documentation for rating control in Asp.net Core and MVC platform.

1. Getting started
2. Precision modes
3. Labels
4. Tooltip
5. Selection
6. Templates
7. Events
8. Appearance
9. Accessibility

### Solution description

Added UG Documentation for rating control in Asp.net Core and MVC platform.

### Output screenshots

NA

### Areas affected and ensured

None (New Component)

### Test cases

NA

### Test bed sample location

NA

### Additional checklist

* Did you run the automation against your implementation? NA
* Is there any API name change? NA.
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? Yes

2023-01-10 13:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2145/console)**

2023-01-11 07:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/console)**

2023-01-11 07:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2158/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-11 10:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2171/console)**

2023-01-11 10:27 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2171/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-01-11 10:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/console)**

2023-01-11 10:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2172/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-11 18:35 UTC, NavinVinayagam requested changes

2023-01-11 18:35 UTC, NavinVinayagam commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
> +You can also customize the appearance of rating component.
rating control

2023-01-11 18:35 UTC, NavinVinayagam commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
> +![Asp.Net MVC Rating Component with Items count](images/rating-items-count.png)
Change rating component to rating control in all places

2023-01-11 18:35 UTC, NavinVinayagam commented on ej2-asp-core-toc.html
> -				<li><a href="/cr/aspnetcore-js2/Syncfusion.EJ2.Inputs.Rating.html">API Reference</a></li>
Why you have removed the API reference link?

2023-01-11 18:35 UTC, NavinVinayagam commented on ej2-asp-mvc-toc.html
> -				<li><a href="/cr/aspnetmvc-js2/Syncfusion.EJ2.Inputs.Rating.html">API Reference</a></li>
Why you have removed the API reference link?

2023-01-12 03:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/console)**

2023-01-12 03:23 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
> +You can also customize the appearance of rating component.
updated as per comments.

2023-01-12 03:23 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/appearance.md
> +![Asp.Net MVC Rating Component with Items count](images/rating-items-count.png)
updated as per comments.

2023-01-12 03:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2181/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-12 03:24 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-toc.html
> -				<li><a href="/cr/aspnetcore-js2/Syncfusion.EJ2.Inputs.Rating.html">API Reference</a></li>
It mistakenly removed when I resolve conflict, now I added API reference link.

2023-01-12 03:24 UTC, VigneshwaranGovindharajan commented on ej2-asp-mvc-toc.html
> -				<li><a href="/cr/aspnetmvc-js2/Syncfusion.EJ2.Inputs.Rating.html">API Reference</a></li>
It mistakenly removed when I resolve conflict, now I added API reference link.

2023-01-12 03:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/console)**

2023-01-12 03:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2182/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-12 05:36 UTC, NavinVinayagam requested changes

2023-01-12 06:33 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/events.md
> +The rating component triggers the [OnItemHover](https://help.syncfusion.com/cr/aspnetmvc-js2/Syncfusion.EJ2.Inputs.Rating.html#Syncfusion_EJ2_Inputs_Rating_OnItemHover) passed as an event argument pr
updated as per comments.

2023-01-12 06:33 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/events.md
> +The rating component triggers the [BeforeItemRender](https://help.syncfusion.com/cr/aspnetmvc-js2/Syncfusion.EJ2.Inputs.Rating.html#Syncfusion_EJ2_Inputs_Rating_BeforeItemRender) event before renderi
updated as per comments.

2023-01-12 06:33 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/tooltip.md
> +You can use the [TooltipTemplate](https://help.syncfusion.com/cr/aspnetmvc-js2/Syncfusion.EJ2.Inputs.Rating.html#Syncfusion_EJ2_Inputs_Rating_TooltipTemplate) tag directive to specify a custom templa
updated as per comments.

2023-01-12 06:33 UTC, VigneshwaranGovindharajan commented on ej2-asp-core-mvc/rating/EJ2_ASP.MVC/labels.md
> +You can use the [LabelTemplate](https://help.syncfusion.com/cr/aspnetmvc-js2/Syncfusion.EJ2.Inputs.Rating.html#Syncfusion_EJ2_Inputs_Rating_LabelTemplate) tag directive to specify a custom template f
updated as per comments.

2023-01-12 06:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/console)**

2023-01-12 06:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2189/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-12 09:37 UTC, NavinVinayagam approved these changes

2023-01-12 09:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/console)**

2023-01-12 09:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2MVC-490-RatingDocs](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2197/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-01-13 07:46 UTC, merged