EJ2-70478-signature
syncfusion-content/ej2-asp-core-mvc-docs pull request #1643
Opened 2023-04-10 10:16 UTC by SaravanaPriya31

2023-04-10 10:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/console)**

2023-04-10 10:21 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/)<br/>**

2023-04-17 10:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2677/console)**

2023-04-17 10:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2677/)<br/>**

2023-04-17 11:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2678/console)**

2023-04-17 11:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2678/)<br/>**

2023-04-19 12:52 UTC, florenceliliana requested changes

2023-04-19 12:52 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/navigation.md
> +The Syncfusion PDF Viewer component supports keyboard navigation for the form fields in a PDF document using the `Tab` and `Shift+Tab` keys. This allows users to easily navigate through the form fiel
The Syncfusion PDF Viewer component supports keyboard navigation for the form fields in a PDF document using the `Tab` and `Shift+Tab` keys. This allows users to easily navigate through the form fields in a PDF document, making it easier to fill out forms.

2023-04-19 12:52 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +The `previousField()` method is used to move the focus to the previous signature field, and the `nextField()` method is used to move the focus to the next signature field.
The `previousField()` method moves the focus to the previous signature field, and the `nextField()` method moves the focus to the next signature field.

2023-04-19 12:52 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +To navigate to the next and previous signature fields programmatically in Syncfusion PDF Viewer.
Navigate to the next and previous signature fields programmatically in the Syncfusion PDF Viewer.

2023-04-19 12:52 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +control: How to navigate to the next and previous signature fields
control: How to navigate to the next and previous signature fields.

2023-04-20 05:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2713/console)**

2023-04-20 06:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2713/)<br/>**

2023-05-02 04:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2723/console)**

2023-05-02 04:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2723/)<br/>**

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/navigation.md
> +The Syncfusion PDF Viewer component supports keyboard navigation for the form fields in a PDF document using the `Tab` and `Shift+Tab` keys. This allows users to easily navigate through the form fiel
The Syncfusion PDF Viewer component supports keyboard navigation for the form fields in a PDF document using the `Tab` and `Shift+Tab` keys. This allows users to easily navigate through the form fields in a PDF document, making it easier to fill out forms.

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +layout: post
Layout: Post

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +title: How to navigate to the next and previous signature fields ##Platform_Name## Pdfviewer Component
Title: How to navigate to the next and previous signature fields ##Platform_Name## Pdfviewer Component

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +description: Learn how to navigate to the next and previous signature fields in Syncfusion ##Platform_Name## Pdfviewer component of Syncfusion Essential JS 2 and more.
Description: Learn how to navigate to the next and previous signature fields in Syncfusion ##Platform_Name## Pdfviewer component of Syncfusion Essential JS 2 and more.

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +platform: ej2-asp-core-mvc
Platform: ej2-asp-core-mvc

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +control: How to navigate to the next and previous signature fields
Control: How to navigate to the next and previous signature fields

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +publishingplatform: ##Platform_Name##
Publishingplatform: ##Platform_Name##

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +documentation: ug
Documentation: UG

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +To use these functions, you need to ensure that the Syncfusion PDF Viewer is properly initialized on the page, and that the formFieldsModule module is loaded.
To use these functions, ensure the Syncfusion PDF Viewer is properly initialized on the page and the formFieldsModule module is loaded.

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +Here's an example of how to use the `previousField()` and `nextField()` method:
The following is an example of using the `previousField()` and `nextField()` methods.

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/navigate-next-previous-signaturefields.md
> +The `previousField()` and `nextField()` methods are called on the formFieldsModule property of the viewer object when the corresponding buttons are clicked. When the functions are called, they use th
The `previousField()` and `nextField()` methods are called on the formFieldsModule property of the viewer object when the corresponding buttons are clicked. When the functions are called, they use the `viewer.formFieldsModule` object to navigate between the form fields in a PDF document.

2023-05-05 07:20 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/navigation.md
> +The Syncfusion PDF Viewer component supports keyboard navigation for the form fields in a PDF document using the `Tab` and `Shift+Tab` keys. This allows users to easily navigate through the form fiel
The Syncfusion PDF Viewer component supports keyboard navigation for the form fields in a PDF document using the `Tab` and `Shift+Tab` keys. This allows users to easily navigate through the form fields in a PDF document, making it easier to fill out forms.

2023-05-15 08:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2747/console)**

2023-05-15 08:32 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2747/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-05-15 08:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2748/)<br/>**

2023-05-25 04:23 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2773/console)**

2023-05-25 04:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2773/console)**

2023-05-25 04:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2773/)<br/>**

2023-05-30 11:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2789/console)**

2023-05-30 11:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-70478-signature](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2789/)<br/>**

2024-04-03 08:46 UTC, closed without merging