EJ2-72229 : How to change the signature indicator text
syncfusion-content/ej2-asp-core-mvc-docs pull request #1662
Opened 2023-04-17 09:04 UTC by SaravanaPriya31

### Description 
How to change the signature indicator text

2023-04-17 09:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2675/)<br/>**

2023-04-19 12:21 UTC, florenceliliana requested changes

2023-04-20 05:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2712/console)**

2023-04-20 05:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2712/)<br/>**

2023-04-23 12:06 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2714/console)**

2023-04-23 12:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2714/console)**

2023-04-23 12:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2714/)<br/>**

2023-04-23 12:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2715/console)**

2023-04-23 12:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2715/)<br/>**

2023-05-02 04:21 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2722/console)**

2023-05-02 04:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2722/console)**

2023-05-02 04:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2722/)<br/>**

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +layout: post
Payout: Post

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +title: How to change the signature indicator settings | Syncfusion
Title: How to change the signature indicator settings | Syncfusion

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +description: Learn how to change the signature indicator settings in Syncfusion ##Platform_Name## Pdfviewer component of Syncfusion Essential JS 2 and more.
Description: Learn how to change the signature indicator settings in Syncfusion ##Platform_Name## Pdfviewer component of Syncfusion Essential JS 2 and more.

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +platform: ej2-asp-core-mvc
Platform: ej2-asp-core-mvc

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +control: How to change the signature indicator settings
Control: How to change the signature indicator settings

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +publishingplatform: ##Platform_Name##
Publishingplatform: ##Platform_Name##

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +documentation: ug
Documentation: UG

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +To change the signature indicator settings in the Syncfusion PDF Viewer, you need to use the `signatureIndicatorSettings` property of the `signatureFieldSettings` object.You can modify various proper
To change the signature indicator settings in the Syncfusion PDF Viewer, use the `signatureIndicatorSettings` property of the `signatureFieldSettings` object. Modify various properties of the signature indicator such as opacity, background color, width, height, font size, text, and color.

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +Here's an example of how to change the signature indicator settings
The following is an example of how to change the signature indicator settings.

2023-05-05 06:33 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/change-signature-indicator-text.md
> +If you want to change any of these properties, you can simply modify the corresponding value in the `signatureIndicatorSettings` object. The same goes for the initial field indicator, too.
If you want to change these properties, simply modify the corresponding value in the `signatureIndicatorSettings` object. The same goes for the initial field indicator.

2023-05-15 08:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2745/console)**

2023-05-15 08:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2745/)<br/>**

2023-05-15 08:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2752/console)**

2023-05-15 09:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2753/console)**

2023-05-15 09:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72229-indicator](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2753/)<br/>**

2024-04-03 08:46 UTC, closed without merging