EJ2-72228 : Hide type and upload signature dialoge in PDF Viewer
syncfusion-content/ej2-asp-core-mvc-docs pull request #1663
Opened 2023-04-17 09:32 UTC by SaravanaPriya31

### Description 

Hide type and upload signature dialoge in PDF Viewer

2023-04-17 09:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2676/console)**

2023-04-17 09:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2676/)<br/>**

2023-04-19 12:26 UTC, florenceliliana requested changes

2023-04-19 12:26 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/hide-type-and-uploadsignature.md
> +# How to Hide the type and upload signature dialogue
# How to Hide the type and upload Signature Dialogue

2023-04-19 12:26 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/hide-type-and-uploadsignature.md
> +To hide the type and upload signature dialogue in Syncfusion PDF Viewer, you can use the following code
You can use the following code to hide the type and upload the signature dialogue in the Syncfusion PDF Viewer.

2023-04-19 12:26 UTC, florenceliliana commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/hide-type-and-uploadsignature.md
> +In the signatureDialogSettings object, set the `hideTypeSignature` and `hideUploadSignature` properties to `true` to hide the type and upload signature dialogue, respectively. Additionally, set the `
In the signatureDialogSettings object, set the `hideTypeSignature` and `hideUploadSignature` properties to `true` to hide the type and upload signature dialogue, respectively. Additionally, set the `hideSaveSignature property` to `true` to hide the Save Signature button. The `displayMode `property controls the display mode of the signature dialog box. Setting it to `0` will hide the dialog box.

2023-04-20 05:40 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2711/)<br/>**

2023-04-23 12:26 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2716/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-04-23 12:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2717/console)**

2023-04-23 12:27 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2717/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-04-23 12:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2718/console)**

2023-04-23 12:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2718/console)**

2023-04-23 12:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2718/)<br/>**

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +layout: post
Layout: Post

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +title: How to Customize Signature Dialog | Syncfusion
Title: How to Customize Signature Dialog | Syncfusion

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +description: Learn how to customize signature dialog in Syncfusion ##Platform_Name## Pdfviewer component of Syncfusion Essential JS 2 and more.
Description: Learn how to customize signature dialog in Syncfusion ##Platform_Name## Pdfviewer component of Syncfusion Essential JS 2 and more.

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +platform: ej2-asp-core-mvc
Platform: ej2-asp-core-mvc

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +control: How to Customize Signature Dialog
Control: How to Customize Signature Dialog

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +publishingplatform: ##Platform_Name##
Publishingplatform: ##Platform_Name##

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +documentation: ug
Documentation: UG

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +To customize the signature dialogue in Syncfusion PDF Viewer. The `signatureFieldSettings` property of the PDF Viewer instance is used to access the signature dialog settings.
Customize the signature dialogue in Syncfusion PDF Viewer. The `signatureFieldSettings` property of the PDF Viewer instance is used to access the signature dialog settings.

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +The `displayMode` property determines the display mode of the signature dialogue. A value of `1` indicates that the signature dialogue should be displayed in a separate window. The `hideTypeSelection
The `displayMode` property determines the display mode of the signature dialogue. A value of `1` indicates that the signature dialogue should be displayed in a separate window. The `hideTypeSelection` property hides the signature field type selection dialogue, allowing users to choose the type of signature field they want to add. The `hideUploadSignature` property is used to hide the upload signature dialogue, which allows users to upload an image file to use as their signature. The `hideSaveSignature` property hides the save signature dialogue, allowing users to save their signature for future use. The `hideDrawSignature` property is set to true, meaning the Draw Signature option will be hidden in the signature dialog.

2023-05-05 07:00 UTC, Chrispineagunja commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.NETCORE/how-to/customize-signature-dialog.md
> +You can modify these properties to suit your needs and customize the signature dialogue in Syncfusion PDF Viewer accordingly.
Modify these properties to suit your needs and customize the signature dialogue in Syncfusion PDF Viewer accordingly.

2023-05-15 08:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2750/)<br/>**

2023-05-15 09:00 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2754/console)**

2023-05-15 09:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2754/console)**

2023-05-15 09:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2754/)<br/>**

2023-05-15 12:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2755/console)**

2023-05-16 08:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2756/console)**

2023-05-16 08:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2756/)<br/>**

2023-05-25 04:23 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2772/console)**

2023-05-25 04:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2772/console)**

2023-05-25 04:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2772/)<br/>**

2023-05-30 11:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2790/console)**

2023-05-30 11:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2790/)<br/>**

2023-06-14 05:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2816/console)**

2023-06-14 05:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-72228-hide](https://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2816/)<br/>**

2024-04-03 08:46 UTC, closed without merging