SEO-174654-ASP-MVC-Controls-ej2-UG
syncfusion-content/ej2-asp-core-mvc-docs pull request #2612
Opened 2024-01-17 13:18 UTC by Omanyadickson

Hi @MallikaRK 

Kindly review my PR below. Thank you.

Regards.
Dickson J

2024-01-17 13:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-ASP-MVC-Controls-ej2-UG](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/246/console)**

2024-01-18 12:20 UTC, Yvone-Atieno requested changes
Commented

2024-01-18 12:20 UTC, Yvone-Atieno commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/getting-started-core.md
> +N> Checkout the [Themes topic](https://ej2.syncfusion.com/aspnetcore/documentation/appearance/theme) to learn different ways ([CDN](https://ej2.syncfusion.com/aspnetcore/documentation/common/adding-s
Check CRG link

2024-01-18 12:33 UTC, Omanyadickson commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/getting-started-core.md
> +N> Checkout the [Themes topic](https://ej2.syncfusion.com/aspnetcore/documentation/appearance/theme) to learn different ways ([CDN](https://ej2.syncfusion.com/aspnetcore/documentation/common/adding-s
Checked

2024-01-18 12:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-ASP-MVC-Controls-ej2-UG](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/258/console)**

2024-01-18 12:35 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-174654-ASP-MVC-Controls-ej2-UG](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/258/)<br/>**

2024-01-18 12:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174654-ASP-MVC-Controls-ej2-UG](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/259/console)**

2024-01-18 12:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174654-ASP-MVC-Controls-ej2-UG](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/259/)<br/>**

2024-01-19 14:03 UTC, Yvone-Atieno approved these changes
Approved

2024-01-22 11:16 UTC, merged