SEO-181942-UG-Duplicate-title
syncfusion-content/ej2-asp-core-mvc-docs pull request #2860
Opened 2024-04-04 09:13 UTC by Edithabich

Hi @MallikaRK ,
Kindly review the duplicate title changes.

Regards,
Edith.

2024-04-04 09:14 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/898/console)**

2024-04-04 09:22 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/898/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-04-04 09:23 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/898/)<br/>**

2024-04-04 09:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/901/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-04 11:59 UTC, MallikaRK requested changes
Commented

2024-04-04 11:59 UTC, MallikaRK commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/annotation/text-markup-annotation.md
> +title: Text Markup Annotation Guide in ##Platform_Name## Pdfviewer Component | Syncfusion
is this meaningful? remove guide here.
Check the control name in FT page and update.

2024-04-04 12:25 UTC, Edithabich commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/annotation/text-markup-annotation.md
> +title: Text Markup Annotation Guide in ##Platform_Name## Pdfviewer Component | Syncfusion
resolved

2024-04-04 12:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/909/console)**

2024-04-12 09:45 UTC, MallikaRK requested changes
commented

2024-04-12 09:45 UTC, MallikaRK commented on ej2-asp-core-mvc/pdfviewer/EJ2_ASP.MVC/annotation/text-markup-annotation.md
> +title: Text Markup Annotation Guide in ##Platform_Name## Pdfviewer Component | Syncfusion
Hi @Edithabich , still my comment is not addressed. Can you remove guide word in Title? also you can use "Support" word here.

2024-04-12 11:33 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/963/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-04-12 11:33 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/963/)<br/>**

2024-04-12 11:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/console)**

2024-04-12 11:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181942-UG-Duplicate-title](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/964/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 11:53 UTC, MallikaRK approved these changes
approved

2024-04-23 13:13 UTC, merged