SEO-187489-ej2-Asp.net-core-Introduction-Page-with-redirect-link
syncfusion-content/ej2-asp-core-mvc-docs pull request #3276
Opened 2024-08-15 12:41 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3275|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187647|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|

Title | Description
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
Changes made | Reason for change
-- | --
| Page with redirect| To increase page performance |

2024-08-15 12:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187489-ej2-Asp.net-core-Introduction-Page-with-redirect-link](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/console)**

2024-08-15 12:43 UTC, SyncfusionBuild commented
The CI [Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2024-08-15 12:43 UTC, Faith-Atieno commented
rebuild

2024-08-15 12:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187489-ej2-Asp.net-core-Introduction-Page-with-redirect-link](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1879/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-15 13:59 UTC, Yvone-Atieno requested changes
Commented

2024-08-15 13:59 UTC, Yvone-Atieno commented on ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md
> +title: Introduction of Syncfusion ##Platform_Name## controls | Syncfusion
Introduction of Syncfusion ##Platform_Name## Controls | Syncfusion

2024-08-15 14:14 UTC, Faith-Atieno commented on ej2-asp-core-mvc/EJ2_ASP.NETCORE/introduction.md
> +title: Introduction of Syncfusion ##Platform_Name## controls | Syncfusion
resolved

2024-08-15 14:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-187489-ej2-Asp.net-core-Introduction-Page-with-redirect-link](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/console)**

2024-08-15 14:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-187489-ej2-Asp.net-core-Introduction-Page-with-redirect-link](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1881/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-16 09:54 UTC, Yvone-Atieno approved these changes
Approved

2024-08-20 14:05 UTC, merged