documentation(EJ2-911245): Port the Culture-based number formats Globalization stability support to all the platforms in Spreadsheet
syncfusion-content/ej2-asp-core-mvc-docs pull request #3364
Opened 2024-09-24 04:16 UTC by DinakarManickam4212

Description:

Need to port the culture-based number formats globalization stability support with preview samples to all the platforms in Spreadsheet.

Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/911245

Content Location: https://ej2.syncfusion.com/documentation/spreadsheet/formatting#culture-based-number-formatting

2024-09-24 04:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/console)**

2024-09-24 04:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2153/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-26 20:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/console)**

2024-09-26 20:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2199/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-09-27 06:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/console)**

2024-09-27 06:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2203/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-10-03 07:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/console)**

2024-10-03 08:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2224/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-03 11:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2232/console)**

2024-10-03 11:42 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2232/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-10-03 11:42 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2232/)<br/>**

2024-10-03 11:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/console)**

2024-10-03 11:45 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/)<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [1](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2233/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-03 11:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/console)**

2024-10-03 11:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2234/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-04 05:35 UTC, sridhar-alagirisamy requested changes

2024-10-04 05:35 UTC, sridhar-alagirisamy commented on ej2-asp-core-mvc/spreadsheet/formatting.md
> +{ "de", new List<object> {
Don't use Dictionary here. directly define only the German locale formats like other platform why defining Dictionary and  adding "de".

2024-10-04 05:35 UTC, sridhar-alagirisamy commented on ej2-asp-core-mvc/spreadsheet/formatting.md
> +    // Mapping culture-based number formats for the "de" culture: The "spreadsheet" parameter is an instance of the spreadsheet component, and the "deLocaleFormats" parameter is an array containing f
In Comments mentioned as deLocaleFormats but above defined variable name as localeFormats .

2024-10-04 05:35 UTC, sridhar-alagirisamy commented on ej2-asp-core-mvc/spreadsheet/formatting.md
> +    ej.spreadsheet.configureLocalizedFormat(spreadsheet, localeFormats['de']);
Use directly the localeFormats as List<object>. Don't added extra "de".

2024-10-04 05:35 UTC, sridhar-alagirisamy commented on ej2-asp-core-mvc/spreadsheet/formatting.md
> +Dictionary<string, List<object>> localeFormats = new Dictionary<string, List<object>> {
Same as above

2024-10-04 05:35 UTC, sridhar-alagirisamy commented on ej2-asp-core-mvc/spreadsheet/formatting.md
> +    // Mapping culture-based number formats for the "de" culture: The "spreadsheet" parameter is an instance of the spreadsheet component, and the "deLocaleFormats" parameter is an array containing f
Same as above.

2024-10-04 05:35 UTC, sridhar-alagirisamy commented on ej2-asp-core-mvc/spreadsheet/formatting.md
> +    ej.spreadsheet.configureLocalizedFormat(spreadsheet, localeFormats['de']);
Same as above.

2024-10-04 06:22 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2240/console)**

2024-10-04 06:27 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2240/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-10-04 06:27 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2240/)<br/>**

2024-10-04 06:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/console)**

2024-10-04 06:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/console)**

2024-10-04 06:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-911245-Dev](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2241/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-04 16:50 UTC, gobalakrishnans approved these changes

2024-10-04 16:53 UTC, sridhar-alagirisamy approved these changes

2024-10-04 16:57 UTC, merged