SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-…
syncfusion-content/ej2-asp-core-mvc-docs pull request #3444
Opened 2024-10-16 12:20 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | SEMrush and Bing reports- Descrition too long|
|Content Task Link/Mail Screenshot | NA|
|Hotfix| https://github.com/syncfusion-content/ej2-asp-core-mvc-docs/pull/3443|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/190701|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B4631D723-2EC0-4999-985A-2FDC8DBD30C5%7D&file=Faith.xlsx&action=default&mobileredirect=true|

Changes Made | Reason for change |
|-- | -- |
|Changed redirect links | To improve performance of the page.|

2024-10-16 12:33 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/)<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2420/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-16 12:44 UTC, Faith-Atieno commented
rebuild

2024-10-16 12:46 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/)<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2421/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-16 13:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2425/console)**

2024-10-16 13:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/console)**

2024-10-16 13:30 UTC, SyncfusionBuild commented
The CI [Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2024-10-16 13:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2426/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-23 11:46 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/console)**

2024-10-23 12:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/console)**

2024-10-23 12:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2457/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-25 07:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/console)**

2024-10-25 07:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2477/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-30 12:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/console)**

2024-10-30 12:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2543/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-08 09:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/console)**

2024-11-08 09:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2587/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-12 13:30 UTC, Yvone-Atieno requested changes
Commented

2024-11-12 13:30 UTC, Yvone-Atieno commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/how-to/bind-complex-data-to-the-pivot-table.md
> +description: Learn here all about how to convert complex JSON to flat JSON and assign it to the pivot table in ##Platform_Name## component of syncfusion and more.
Update proper title and H1

2024-11-13 06:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/console)**

2024-11-13 06:36 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/)<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2657/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-13 07:34 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/console)**

2024-11-13 07:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/console)**

2024-11-13 07:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2661/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-13 13:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2668/console)**

2024-11-13 13:27 UTC, Faith-Atieno commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/how-to/bind-complex-data-to-the-pivot-table.md
> +description: Learn here all about how to convert complex JSON to flat JSON and assign it to the pivot table in ##Platform_Name## component of syncfusion and more.
resolved

2024-11-15 07:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/console)**

2024-11-15 08:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/console)**

2024-11-15 08:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2683/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-22 06:31 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/console)**

2024-11-22 06:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/console)**

2024-11-22 06:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2725/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-28 06:07 UTC, Yvone-Atieno requested changes
Commented

2024-11-29 07:13 UTC, Yvone-Atieno requested changes
Commented

2024-11-29 07:13 UTC, Yvone-Atieno commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/how-to/bind-complex-data-to-the-pivot-table.md
> +# Bind complex data to the pivot table in ##Platform_Name##
Update proper H1

2024-12-03 15:18 UTC, Faith-Atieno commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/how-to/bind-complex-data-to-the-pivot-table.md
> +# Bind complex data to the pivot table in ##Platform_Name##
resolved

2024-12-04 08:44 UTC, Yvone-Atieno requested changes
Commented

2024-12-04 08:44 UTC, Yvone-Atieno commented on ej2-asp-core-mvc/pivot-table/EJ2_ASP.NETCORE/how-to/bind-complex-data-to-the-pivot-table.md
> +title: Convert complex JSON to flat JSON in ##Platform_Name## pivot table | Syncfusion
Check the updated title

2024-12-04 09:39 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2895/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-12-04 09:39 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2895/)<br/>**

2024-12-04 09:40 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/console)**

2024-12-04 09:42 UTC, closed without merging

2024-12-04 09:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/console)**

2024-12-04 09:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-190701--EJ2-ASP.NET-CORE-pivot-table-how-to-bind-complex-data-to-the-pivot-table-Description-too-long](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2896/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**