914703: Documentation of rows topic in development
syncfusion-content/ej2-asp-core-mvc-docs pull request #3446
Opened 2024-10-16 13:07 UTC by Vinitha-Balasubramanian

Revamped the rows documentation in development branch

2024-10-16 13:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2423/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-21 06:35 UTC, MaithiliyK commented on ej2-asp-core-mvc/code-snippet/grid/row/add-row/razor
> +     // Generate a random Freight value
comments is wrong it is ShipName you mentioned freight again

2024-10-21 06:45 UTC, MaithiliyK commented on ej2-asp-core-mvc/code-snippet/grid/row/format-row-template/razor
> +   .CardHeader {
css naming is not in standard use small letter for css class

2024-10-21 06:47 UTC, MaithiliyK commented on ej2-asp-core-mvc/code-snippet/grid/row/format-row-template/tagHelper
> +       border-width: 1px 0px 0px 0px;
this property is same in photo and detail class then why you are not defining the css in the above class please do the changes in entire doc

2024-10-21 06:48 UTC, MaithiliyK commented on ej2-asp-core-mvc/code-snippet/grid/row/frozen-rows-style/razor
> +  col.Field("EmployeeID").HeaderText("EmployeeID").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Right).Add();
check the header text value in all the samples it must be displayed with space between two word Like Employee ID not EmployeeID

2024-10-21 07:11 UTC, MaithiliyK commented on ej2-asp-core-mvc/code-snippet/grid/row/format-row-template/razor
> +       return dFormatter(date);
check the naming standard

2024-10-21 07:23 UTC, MaithiliyK commented on ej2-asp-core-mvc/grid/EJ2_ASP.MVC/row/row-drag-and-drop.md
> +![Drag and drop to custom component](../../images/row/drag-drop-tree-grid.gif)
is the image path is correction?. Since recently you changed the image path to relative path

2024-10-21 07:27 UTC, MaithiliyK commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row-template.md
> +By default, Syncfusion Grid provides the `columns.format` property to format the values displayed in each column. However, when using the [rowtemplate](https://help.syncfusion.com/cr/aspnetcore-js2/S
API name casing is wrong why API name is not given for columns.format

2024-10-21 07:30 UTC, MaithiliyK commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row.md
> +> * You can use both  [FrozenColumns](https://ej2.syncfusion.com/aspnetcore/documentation/grid/columns/frozen-column) property and `FrozenRows` property in the same application.
API name casing is wrong

2024-10-21 07:31 UTC, MaithiliyK commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row.md
> +* Frozen row is not compatible with the following features:
make it as single sentence since we have mentioned only one feature only so dont go with bulleted format

2024-10-21 07:33 UTC, MaithiliyK requested changes
address my review correction

2024-10-21 12:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/console)**

2024-10-21 12:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2441/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row.md
> +* Frozen row is not compatible with the following features:
modified the limitation into single sentence

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row.md
> +> * You can use both  [FrozenColumns](https://ej2.syncfusion.com/aspnetcore/documentation/grid/columns/frozen-column) property and `FrozenRows` property in the same application.
changed the casing of API.

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/row/row-template.md
> +By default, Syncfusion Grid provides the `columns.format` property to format the values displayed in each column. However, when using the [rowtemplate](https://help.syncfusion.com/cr/aspnetcore-js2/S
format property doesn't have API reference

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/grid/EJ2_ASP.MVC/row/row-drag-and-drop.md
> +![Drag and drop to custom component](../../images/row/drag-drop-tree-grid.gif)
modified the image path to relative path

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/code-snippet/grid/row/format-row-template/razor
> +       return dFormatter(date);
changed variable name

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/code-snippet/grid/row/frozen-rows-style/razor
> +  col.Field("EmployeeID").HeaderText("EmployeeID").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Right).Add();
checked and updated the header text for all the sample of row topics.

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/code-snippet/grid/row/format-row-template/tagHelper
> +       border-width: 1px 0px 0px 0px;
changed the mentioned css property.

2024-10-21 12:43 UTC, Vinitha-Balasubramanian commented on ej2-asp-core-mvc/code-snippet/grid/row/add-row/razor
> +     // Generate a random Freight value
modified the comments for the ship name function.

2024-10-21 13:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/console)**

2024-10-21 13:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2444/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-22 03:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/console)**

2024-10-22 04:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-914703-rows-dev-new](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2447/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-22 05:07 UTC, MaithiliyK approved these changes
changes are fine

2024-10-22 05:07 UTC, merged