844271: ASP-Need to add how to section to explain addNodes, updateNode, refreshNode, moveNodes and removeNodes method in TreeView documentation.
syncfusion-content/ej2-asp-core-mvc-docs pull request #3475
Opened 2024-10-29 05:26 UTC by suba-1997

### Bug description
ASP Need to add how to section to explain addNodes, updateNode, refreshNode, moveNodes and removeNodes method in TreeView documentation.

### Root cause
The mentioned methods are not documented earlier in ASP documentation.

### Solution description
We have included the separate page as User interactions in How To section.

### Reason for not identifying earlier
 * [] Guidelines not followed. If yes, provide which guideline is not followed.

 * [ ] Guidelines not given. If yes, provide which/who need to address.
    Tag label `update-guideline-coreteam` or `update-guideline-productteam`. 

 * [X] If any other reason, provide the details here. 
 Based on the customer raised queries, we have decided to document these methods in ASP.

### Output screenshots
#### refreshNode method:
#### Before:
![image](https://github.com/user-attachments/assets/030f9827-1ee4-4db4-9d4d-c81793fe0578)

#### After:
![image](https://github.com/user-attachments/assets/aaf1278b-b432-4d5d-9197-889b65ae1cb4)

### Reviewer Checklist
* []  All provided information are reviewed and ensured.

2024-10-29 05:27 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2504/console)**

2024-10-29 06:06 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2504/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-10-29 06:07 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2504/)<br/>**

2024-10-29 06:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/console)**

2024-10-29 07:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/console)**

2024-10-29 07:40 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/)<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2505/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-29 10:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/console)**

2024-10-29 10:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2516/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-29 10:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/console)**

2024-10-29 10:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2517/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-29 10:30 UTC, kmkrish001 requested changes

2024-10-29 10:30 UTC, kmkrish001 commented on ej2-asp-core-mvc/code-snippet/treeview/how-to/user-interactions-cs2/razor
> +        // The node with id 21 is removed from the TreeView component.
in comment mentioned as id 21 but in code it is 14

2024-10-29 10:30 UTC, kmkrish001 commented on ej2-asp-core-mvc/code-snippet/treeview/how-to/user-interactions-cs2/tagHelper
> +        // The node with id 21 is removed from the TreeView component.
change comment

2024-10-29 10:46 UTC, suba-1997 commented on ej2-asp-core-mvc/code-snippet/treeview/how-to/user-interactions-cs2/razor
> +        // The node with id 21 is removed from the TreeView component.
comment changed.

2024-10-29 10:46 UTC, suba-1997 commented on ej2-asp-core-mvc/code-snippet/treeview/how-to/user-interactions-cs2/tagHelper
> +        // The node with id 21 is removed from the TreeView component.
comment changed.

2024-10-29 10:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/console)**

2024-10-29 10:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2518/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-29 11:59 UTC, kmkrish001 approved these changes

2024-10-29 18:14 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/console)**

2024-10-30 04:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/console)**

2024-10-30 04:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-844271-TV](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2532/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-04 07:06 UTC, closed without merging