Documentation(896237-columnTemplate-hotfix): Revamp for Column templa…
syncfusion-content/ej2-asp-core-mvc-docs pull request #3573
Opened 2024-11-29 05:57 UTC by Gayathri4135

…te in ASP.NET CORE and MVC

2024-11-29 05:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/console)**

2024-11-29 06:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2862/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-29 07:22 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/console)**

2024-11-29 07:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/console)**

2024-11-29 07:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2864/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-02 05:51 UTC, VigneshNatarajan27 commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-template.md
> +The following example demonstrates how to add template column using external button click. In this example, the **ShipCountry** column with a [Dropdownlist](https://ej2.syncfusion.com/aspnetcore/docu
an icon is displayed in the column header

2024-12-02 05:55 UTC, VigneshNatarajan27 commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-template.md
> +In the following code, we rendered the ColorPicker control in the Grid column by defining the `Template` property.
Template T is in caps. while in other topic t is small letter.

Ensure in all topics

2024-12-02 05:56 UTC, VigneshNatarajan27 approved these changes
Changes proposed. 

Ensure the changes in both MVC and core topics

2024-12-02 05:58 UTC, VigneshNatarajan27 requested changes
Changes proposed. 

Ensure changes in MVC and Core. 

Also do these changes in hotfix and dev

2024-12-02 06:47 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/console)**

2024-12-02 07:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2872/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-02 07:06 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/console)**

2024-12-02 07:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2874/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-02 07:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-columnTemplate-896237](https://ci.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/2876/console)**

2024-12-02 07:37 UTC, Gayathri4135 commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-template.md
> +The following example demonstrates how to add template column using external button click. In this example, the **ShipCountry** column with a [Dropdownlist](https://ej2.syncfusion.com/aspnetcore/docu
Modified in both mvc and core file

2024-12-02 07:37 UTC, Gayathri4135 commented on ej2-asp-core-mvc/grid/EJ2_ASP.NETCORE/columns/column-template.md
> +The following example demonstrates how to use a custom helper function inside the `template` property, using the `template` element for the Freight column.
Modified the both mvc and core md file

2024-12-02 09:07 UTC, VigneshNatarajan27 approved these changes
changes are fine

2024-12-02 09:07 UTC, merged