story(EJ2-64028):Port the missing topics in Data Binding and Managing tasks in coreMvc
syncfusion-content/ej2-asp-core-mvc-docs pull request #857
Opened 2022-09-22 13:11 UTC by SridharanJayabalan

**Description**

Ported the missing topics in CoreMvc docs :

Data Binding - Remote data adaptor
Managing Tasks - Read Only Gantt

2022-09-22 13:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/console)**

2022-09-22 13:15 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [5](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1294/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-22 13:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/console)**

2022-09-22 13:47 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1296/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-23 05:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/console)**

2022-09-23 05:36 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1299/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-23 05:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/console)**

2022-09-23 05:50 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1300/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-23 09:49 UTC, SridharanJayabalan commented
rebuild

2022-09-23 09:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/console)**

2022-09-23 09:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1308/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-30 08:40 UTC, alansangeeths commented on ej2-asp-core-mvc/gantt/data-binding.md
> +Datasource must be set to the **json** property and set **RemoteSaveAdaptor** to the **adaptor** property. CRUD operations can be mapped to the server-side by using the **batchUrl** properties.
adaptor property of DataManager

2022-09-30 08:40 UTC, alansangeeths commented on ej2-asp-core-mvc/gantt/managing-tasks/managing-tasks.md
> +In Gantt, all create, update, delete operations can be disabled by set `readOnly` property as `true`. The following sample demonstrates, render Gantt chart as read only.
by setting readonly

2022-09-30 08:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1482/console)**

2022-09-30 08:50 UTC, SyncfusionBuild commented
The running **[CI Job](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1482/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-09-30 08:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/console)**

2022-09-30 08:52 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1483/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-30 10:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/console)**

2022-09-30 10:42 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1488/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-30 12:30 UTC, SridharanJayabalan commented
rebuild

2022-09-30 12:31 UTC, SyncfusionBuild commented
The running **[CI Job](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1491/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-09-30 12:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/console)**

2022-09-30 12:39 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1492/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-30 12:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/console)**

2022-09-30 13:02 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1493/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-03 04:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/console)**

2022-10-03 04:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1494/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-03 13:58 UTC, florenceliliana requested changes

2022-10-03 13:58 UTC, florenceliliana commented on ej2-asp-core-mvc/gantt/data-binding.md
> +You may need to perform all Gantt Actions on the client-side except the CRUD operations, that should be interacted with the server-side to persist data. It can be achieved in Gantt by using **RemoteS
You may need to perform all Gantt Actions on the client-side except the CRUD operations, which should be interacted with the server-side to persist data. It can be achieved in Gantt using **RemoteSaveAdaptor.**

2022-10-05 05:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/console)**

2022-10-05 05:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1541/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-05 05:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1542/console)**

2022-10-05 05:24 UTC, SyncfusionBuild commented
The running **[CI Job](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1542/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2022-10-05 05:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/console)**

2022-10-05 05:32 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1543/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-05 06:06 UTC, SridharanJayabalan commented
rebuild

2022-10-05 06:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/console)**

2022-10-05 06:17 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1544/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-05 06:19 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/console)**

2022-10-05 06:23 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/)<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1545/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-05 10:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/console)**

2022-10-05 10:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [EJ2-64028-addtopics](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/ej2-asp-core-mvc-docs/1552/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-10-06 13:09 UTC, MahalakshmiKarthikeyan approved these changes

2022-10-06 13:10 UTC, merged